export const footerTexts = {
  en: {
    quickLinks: "Quick Links",
    home: "Home",
    aboutUs: "About Us",
    services: "Services",
    contact: "Contact",
    ourServices: "Our Services",
    viewAllServices: "View All Services",
    getInTouch: "Get In Touch",
    callUs: "Call Us",
    email: "Email",
    location: "Location",
    rightsReserved: "All Rights Reserved.",
    address1: "Showroom No-7, AJD Building,",
    address2: "Umm Ramool, Rashidiya,",
    address3: "Dubai, UAE",
  },

  ar: {
    quickLinks: "روابط سريعة",
    home: "الرئيسية",
    aboutUs: "من نحن",
    services: "الخدمات",
    contact: "اتصل بنا",
    ourServices: "خدماتنا",
    viewAllServices: "عرض جميع الخدمات",
    getInTouch: "تواصل معنا",
    callUs: "اتصل بنا",
    email: "البريد الإلكتروني",
    location: "الموقع",
    rightsReserved: "جميع الحقوق محفوظة.",
    address1: "معرض رقم -7، مبنى AJD،",
    address2: "أم رمول، الراشدية،",
    address3: "دبي، الإمارات",
  },
};
