export const serviceSectionTexts = {
  en: {
    subtitle: "Our services",
    title: "We have a wide range of services",
    description: "At vitae commodo amet libero tortor blandit risus condimentum mauris. cras arcu tortor aenean turpis massa mauris ac mi facilisi cursus aliquam a ac.",
    viewDetail: "View Detail",
    bgText: "services",
    services: [
      {
        number: '01',
        title: 'Maintenance',
        description: 'Expert car maintenance services to keep your vehicle running smoothly and efficiently. Regular maintenance helps prevent costly repairs and extends your cars lifespan.',
        href: '/services/maintenance',
        alt: 'Car Maintenance Service',
        imgSrc: 'https://wallpaperaccess.com/full/8857411.jpg',
      },
      {
        number: '02',
        title: 'Wheels',
        description: 'Professional wheel services including installation, balancing, and custom wheel fitting. We offer a wide selection of premium wheels to enhance your vehicles performance and look.',
        href: '/services/wheels',
        alt: 'Custom Wheel Services',
        imgSrc: 'https://wordpress-content.vroomly.com/wp-content/uploads/2023/03/iStock-1368159665_2.jpg',
      },
      {
        number: '03',
        title: 'Alignment',
        description: 'Precise wheel alignment services to ensure optimal tire wear and handling. Proper alignment improves fuel efficiency and ensures a smoother, safer driving experience.',
        href: '/services/alignment',
        alt: 'Wheel Alignment Service',
        imgSrc: 'https://i0.wp.com/picjumbo.com/wp-content/uploads/washing-white-suv-in-self-service-car-wash-with-a-wap-hose-free-photo.jpg?w=2210&quality=70',
      },
      {
        number: '04',
        title: 'Powder coating',
        description: 'High-quality powder coating services for wheels and automotive parts. Our durable finish protects against corrosion while providing a superior aesthetic appearance.',
        href: '/services/powder-coating',
        alt: 'Powder Coating Service',
        imgSrc: 'https://www.garagedannythibert.com/ressources/images/8e6996bf7047.jpg',
      },
      {
        number: '05',
        title: 'Brakes',
        description: 'Complete brake service and repair, ensuring your safety on the road. We offer premium brake parts and expert installation for optimal braking performance.',
        href: '/services/brakes',
        alt: 'Brake Service and Repair',
        imgSrc: 'https://www.forum-badharzburg.de/wp-content/uploads/2017/09/bigstock-Portrait-of-an-auto-mechanic-a-91601333.jpg',
      },
      {
        number: '06',
        title: 'Engine service',
        description: 'Comprehensive engine maintenance and repair services. From tune-ups to major repairs, our certified technicians keep your engine running at peak performance.',
        href: '/services/engine-service',
        alt: 'Engine Service and Repair',
        imgSrc: 'https://www.garagedannythibert.com/ressources/images/8e6996bf7047.jpg',
      },
    ]
  },
  ar: {
    subtitle: "خدماتنا",
    title: "لدينا مجموعة واسعة من الخدمات",
    description: "خدمات صيانة السيارات الاحترافية للحفاظ على سيارتك تعمل بسلاسة وكفاءة. الصيانة الدورية تساعد في منع الإصلاحات المكلفة وتطيل عمر سيارتك.",
    viewDetail: "عرض التفاصيل",
    bgText: "الخدمات",
    services: [
      {
        number: '01',
        title: 'الصيانة',
        description: 'خدمات صيانة السيارات الاحترافية للحفاظ على سيارتك تعمل بسلاسة وكفاءة. الصيانة الدورية تساعد في منع الإصلاحات المكلفة وتطيل عمر سيارتك.',
        href: '/services/maintenance',
        alt: 'خدمة صيانة السيارات',
        imgSrc: 'https://wallpaperaccess.com/full/8857411.jpg',
      },
      {
        number: '02',
        title: 'العجلات',
        description: 'خدمات العجلات الاحترافية بما في ذلك التركيب والاتزان وتركيب العجلات المخصصة. نقدم مجموعة واسعة من العجلات الفاخرة لتعزيز أداء ومظهر سيارتك.',
        href: '/services/wheels',
        alt: 'خدمات العجلات المخصصة',
        imgSrc: 'https://wordpress-content.vroomly.com/wp-content/uploads/2023/03/iStock-1368159665_2.jpg',
      },
      {
        number: '03',
        title: 'وزن الأذرعة',
        description: 'خدمات وزن الأذرعة الدقيقة لضمان تآكل الإطارات بشكل مثالي وتحسين التحكم. الوزن الصحيح يحسن كفاءة الوقود ويضمن قيادة أكثر سلاسة وأمانًا.',
        href: '/services/alignment',
        alt: 'خدمة وزن الأذرعة',
        imgSrc: 'https://i0.wp.com/picjumbo.com/wp-content/uploads/washing-white-suv-in-self-service-car-wash-with-a-wap-hose-free-photo.jpg?w=2210&quality=70',
      },
      {
        number: '04',
        title: 'طلاء البودرة',
        description: 'خدمات طلاء البودرة عالية الجودة للعجلات وقطع السيارات. يوفر الطلاء المتين حماية ضد التآكل ويمنح مظهرًا جماليًا مميزًا.',
        href: '/services/powder-coating',
        alt: 'خدمة طلاء البودرة',
        imgSrc: 'https://www.garagedannythibert.com/ressources/images/8e6996bf7047.jpg',
      },
      {
        number: '05',
        title: 'الفرامل',
        description: 'خدمة وإصلاح الفرامل بالكامل لضمان سلامتك على الطريق. نقدم قطع فرامل عالية الجودة وتركيبًا احترافيًا لأداء فرامل مثالي.',
        href: '/services/brakes',
        alt: 'خدمة وإصلاح الفرامل',
        imgSrc: 'https://www.forum-badharzburg.de/wp-content/uploads/2017/09/bigstock-Portrait-of-an-auto-mechanic-a-91601333.jpg',
      },
      {
        number: '06',
        title: 'خدمة المحرك',
        description: 'خدمات صيانة وإصلاح المحرك الشاملة. من الضبط إلى الإصلاحات الكبيرة، يضمن فنيو الخدمة المعتمدون لدينا تشغيل المحرك بأفضل أداء.',
        href: '/services/engine-service',
        alt: 'خدمة وصيانة المحرك',
        imgSrc: 'https://www.garagedannythibert.com/ressources/images/8e6996bf7047.jpg',
      },
    ]
  }
};
